version: '3.9'
services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: ci_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ..:/workspace
    working_dir: /workspace
    environment:
      - JUPYTER_TOKEN=ensmartil
